/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWorkersRouteImport } from './routes/_authenticated/workers'
import { Route as AuthenticatedTeachersRouteImport } from './routes/_authenticated/teachers'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedMarksRouteImport } from './routes/_authenticated/marks'
import { Route as AuthenticatedHarvestRouteImport } from './routes/_authenticated/harvest'
import { Route as AuthenticatedFinanceRouteImport } from './routes/_authenticated/finance'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'
import { Route as AuthenticatedAttendanceRouteImport } from './routes/_authenticated/attendance'
import { Route as AuthenticatedStudentsIndexRouteImport } from './routes/_authenticated/students/index'
import { Route as AuthenticatedStudentsIdRouteImport } from './routes/_authenticated/students/$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWorkersRoute = AuthenticatedWorkersRouteImport.update({
  id: '/workers',
  path: '/workers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeachersRoute = AuthenticatedTeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMarksRoute = AuthenticatedMarksRouteImport.update({
  id: '/marks',
  path: '/marks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHarvestRoute = AuthenticatedHarvestRouteImport.update({
  id: '/harvest',
  path: '/harvest',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanceRoute = AuthenticatedFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAttendanceRoute = AuthenticatedAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudentsIndexRoute =
  AuthenticatedStudentsIndexRouteImport.update({
    id: '/students/',
    path: '/students/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentsIdRoute = AuthenticatedStudentsIdRouteImport.update({
  id: '/students/$id',
  path: '/students/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/harvest': typeof AuthenticatedHarvestRoute
  '/marks': typeof AuthenticatedMarksRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/teachers': typeof AuthenticatedTeachersRoute
  '/workers': typeof AuthenticatedWorkersRoute
  '/students/$id': typeof AuthenticatedStudentsIdRoute
  '/students/': typeof AuthenticatedStudentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/harvest': typeof AuthenticatedHarvestRoute
  '/marks': typeof AuthenticatedMarksRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/teachers': typeof AuthenticatedTeachersRoute
  '/workers': typeof AuthenticatedWorkersRoute
  '/students/$id': typeof AuthenticatedStudentsIdRoute
  '/students': typeof AuthenticatedStudentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/attendance': typeof AuthenticatedAttendanceRoute
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/finance': typeof AuthenticatedFinanceRoute
  '/_authenticated/harvest': typeof AuthenticatedHarvestRoute
  '/_authenticated/marks': typeof AuthenticatedMarksRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/teachers': typeof AuthenticatedTeachersRoute
  '/_authenticated/workers': typeof AuthenticatedWorkersRoute
  '/_authenticated/students/$id': typeof AuthenticatedStudentsIdRoute
  '/_authenticated/students/': typeof AuthenticatedStudentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/attendance'
    | '/audit'
    | '/dashboard'
    | '/finance'
    | '/harvest'
    | '/marks'
    | '/reports'
    | '/settings'
    | '/teachers'
    | '/workers'
    | '/students/$id'
    | '/students/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/attendance'
    | '/audit'
    | '/dashboard'
    | '/finance'
    | '/harvest'
    | '/marks'
    | '/reports'
    | '/settings'
    | '/teachers'
    | '/workers'
    | '/students/$id'
    | '/students'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/attendance'
    | '/_authenticated/audit'
    | '/_authenticated/dashboard'
    | '/_authenticated/finance'
    | '/_authenticated/harvest'
    | '/_authenticated/marks'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/_authenticated/teachers'
    | '/_authenticated/workers'
    | '/_authenticated/students/$id'
    | '/_authenticated/students/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/workers': {
      id: '/_authenticated/workers'
      path: '/workers'
      fullPath: '/workers'
      preLoaderRoute: typeof AuthenticatedWorkersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teachers': {
      id: '/_authenticated/teachers'
      path: '/teachers'
      fullPath: '/teachers'
      preLoaderRoute: typeof AuthenticatedTeachersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/marks': {
      id: '/_authenticated/marks'
      path: '/marks'
      fullPath: '/marks'
      preLoaderRoute: typeof AuthenticatedMarksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/harvest': {
      id: '/_authenticated/harvest'
      path: '/harvest'
      fullPath: '/harvest'
      preLoaderRoute: typeof AuthenticatedHarvestRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance': {
      id: '/_authenticated/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AuthenticatedFinanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/attendance': {
      id: '/_authenticated/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AuthenticatedAttendanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/students/': {
      id: '/_authenticated/students/'
      path: '/students'
      fullPath: '/students/'
      preLoaderRoute: typeof AuthenticatedStudentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/students/$id': {
      id: '/_authenticated/students/$id'
      path: '/students/$id'
      fullPath: '/students/$id'
      preLoaderRoute: typeof AuthenticatedStudentsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAttendanceRoute: typeof AuthenticatedAttendanceRoute
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFinanceRoute: typeof AuthenticatedFinanceRoute
  AuthenticatedHarvestRoute: typeof AuthenticatedHarvestRoute
  AuthenticatedMarksRoute: typeof AuthenticatedMarksRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTeachersRoute: typeof AuthenticatedTeachersRoute
  AuthenticatedWorkersRoute: typeof AuthenticatedWorkersRoute
  AuthenticatedStudentsIdRoute: typeof AuthenticatedStudentsIdRoute
  AuthenticatedStudentsIndexRoute: typeof AuthenticatedStudentsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAttendanceRoute: AuthenticatedAttendanceRoute,
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFinanceRoute: AuthenticatedFinanceRoute,
  AuthenticatedHarvestRoute: AuthenticatedHarvestRoute,
  AuthenticatedMarksRoute: AuthenticatedMarksRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTeachersRoute: AuthenticatedTeachersRoute,
  AuthenticatedWorkersRoute: AuthenticatedWorkersRoute,
  AuthenticatedStudentsIdRoute: AuthenticatedStudentsIdRoute,
  AuthenticatedStudentsIndexRoute: AuthenticatedStudentsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
